### ISSUE TITLE
Readme needed

### ISSUE THREAD

**Issue by Ubuntufanboy** [Flyves/Dropshot-Renderer#1]
I think that a readme is needed! How should people know hot to use it if it has no documentation!

**Comment by PladsElsker** [comment]
If you are comming from the youtube video I posted last month, this is not the same thing at all.
In the video, I draw linart in realtime with boost.

This repo is for drawing images on the dropshot field. It's a rendering process that can take many days.

I didn't really program either of them in a way that is easily accessible to a lot of people, but I can probably provide basic info to get started.
Let me know if you're still interested in this repo or the other one that I haven't released.

**Comment by PladsElsker** [comment]
I added the readme. I don't do this often, hopefully it's good enough!
